org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.debug=false

## Environment Properties
minecraft_version=1.20.4
minecraft_version_range=[1.20.4,)
neo_version=20.4.223
neo_version_range=[20.2,)
loader_version_range=[2,)
curios_version=7.3.4


## Mod Properties
mod_id=curious_armor_stands
mod_name=Curious Armor Stands
mod_license=MIT
mod_version=1.20.4-6.1.0
mod_group_id=curiousarmorstands
mod_authors=ochotonida
mod_description=Allows armor stands to display curios